/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/designs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all designs
         * @description Retrieve all designs available in your Abyssale workspace. Each design defines
         *     the visual layout, available formats (dimensions), and configurable elements
         *     (text, images, shapes, etc.) that can be overridden during image generation.
         *     Filter by design type or project category using query parameters.
         */
        get: operations["listDesigns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/designs/{designId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get design details
         * @description Retrieve the full specification of a design: its formats (dimensions and preview URLs),
         *     all configurable elements with their properties, and any template variables defined
         *     in text layers. Use this endpoint to discover what data to send in a generation request.
         */
        get: operations["getDesign"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/designs/{designId}/formats/{formatSpecifier}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get format details
         * @description Retrieve detailed information for a specific format within a design, including
         *     dimensions, unit, preview URL, dynamic image URL, element layout, and variables.
         *     Useful for inspecting a single format before generating or building dynamic image URLs.
         */
        get: operations["getDesignFormat"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/designs/{designId}/dynamic-image-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a dynamic image URL
         * @description Creates a dynamic image URL for a given design. Only one dynamic image is allowed per design. Subsequent calls return the existing dynamic image. Use `enable_rate_limit` in the request body to enable API rate limiting for this image & `enable_production_mode` to enable production mode (default is test mode).
         */
        post: operations["createDynamicImageUrl"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/banners/{bannerId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get generated file
         * @description Retrieve the metadata and download URLs for a previously generated file
         *     (image, video, GIF, HTML5 banner, or PDF). Returns both the S3 storage URL
         *     and a CDN-hosted URL suitable for embedding directly in websites or emails.
         */
        get: operations["getFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/banner-builder/{designId}/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate an image (synchronous)
         * @description Synchronously generate a single image from a design. Send your dynamic data
         *     (text, images, colors) as element overrides in the request body and receive
         *     the generated file URL immediately in the response.
         *
         *     Best for: real-time image generation, single-asset workflows, or when you need
         *     the result inline without polling.
         *
         *     For bulk generation across multiple formats, use the asynchronous endpoint instead.
         */
        post: operations["generateImage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/async/banner-builder/{designId}/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate images/videos/PDFs asynchronously (multi-format)
         * @description Asynchronously generate multiple formats of an image, video, GIF, HTML5 banner,
         *     or PDF in a single API call. Ideal for bulk banner production, multi-channel
         *     marketing campaigns, and programmatic ad creative generation at scale.
         *
         *     Specify one or more format IDs to generate, or omit the list to generate all
         *     formats defined in the design. Provide a `callback_url` to receive a webhook
         *     notification when generation is complete, or poll
         *     `GET /generation-request/{generationRequestId}` for status.
         *
         *     You can find available formats and elements by calling `GET /designs/{designId}`.
         */
        post: operations["generateMultiFormatMedia"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fonts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List available fonts
         * @description Retrieve all fonts available in your Abyssale workspace, including Google Fonts
         *     and any custom fonts you have uploaded. Use a font's `id` to override the font
         *     on text or button elements in a generation request.
         */
        get: operations["listFonts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/async/banners/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Export banners as ZIP archive (asynchronous)
         * @description Asynchronously package a set of previously generated banners into a single ZIP
         *     archive for download. Provide a `callback_url` to receive a webhook notification
         *     when the export is ready, containing the archive URL.
         */
        post: operations["exportBanners"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/async/banner-builder/{designId}/generate-multipage-pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate a multi-page PDF (asynchronous)
         * @description Asynchronously generate a multi-page print-ready PDF from a printer_multipage design.
         *     Each page is defined by a `pages` dictionary entry, allowing different element
         *     overrides per page — ideal for brochures, catalogs, and variable data printing.
         *
         *     Provide a `callback_url` to receive a webhook when the PDF is ready,
         *     or poll `GET /generation-request/{generationRequestId}` for status.
         *
         *     You can find available formats and elements by calling `GET /designs/{designId}`.
         */
        post: operations["generateMultiPagePdf"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/generation-request/{generationRequestId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Poll async generation request status
         * @description Poll the status of an asynchronous generation request. Use this endpoint to track
         *     the progress of a batch generation operation started with the async generate endpoint.
         *     The result is available for 7 days after generation.
         */
        get: operations["getGenerationRequest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List projects
         * @description Retrieve all projects in your workspace. Projects group designs into logical
         *     collections. Only designs that belong to a project are accessible via the API.
         */
        get: operations["listProjects"];
        put?: never;
        /**
         * Create a project
         * @description Create a new project to organize your designs. Assign designs to this project
         *     in the Abyssale editor to make them accessible via the API.
         */
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspace-templates/{companyTemplateId}/use": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Duplicate a workspace template into a project
         * @description Copy a shared workspace template into one of your projects, creating an editable
         *     design instance. The duplication is asynchronous — use the returned
         *     `duplication_request_id` to poll for completion via
         *     `GET /design-duplication-requests/{duplicateRequestId}`.
         */
        post: operations["duplicateWorkspaceTemplate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/design-duplication-requests/{duplicateRequestId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Poll template duplication request status
         * @description Poll the status of a template duplication request. Use this endpoint to track
         *     the progress of an asynchronous duplication operation.
         */
        get: operations["getDuplicationRequest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            /** @description Human-readable error message. */
            message: string;
            /**
             * @description Machine-readable error code identifier. Present on most errors.
             *
             *     Common values: `template_not_found`, `template_not_static`, `format_not_found`,
             *     `cannot_build_banner`, `rate_limit_exceeded`, `unauthorized`, `api_access_denied`,
             *     `endpoint_not_found`, `body_validation_errors`, `internal_server_error`.
             */
            id?: string;
            /**
             * @description Field-level validation errors, present on 400 responses when `message` is
             *     `"Invalid parameters"`. Each entry identifies the failing field and the reason.
             */
            errors?: {
                /** @description Dot-notation path to the invalid field (e.g. `elements.root.background_color`). */
                field: string;
                /** @description Human-readable reason the field failed validation. */
                message: string;
            }[];
        };
        Banner: {
            /**
             * Format: uuid
             * @example 64238d01-d402-474b-8c2d-fbc957e9d290
             */
            id: string;
            /**
             * @description Version number of the generated file.
             * @example 1
             */
            version?: number;
            /**
             * Format: uuid
             * @description Identifier used for sharing this generated file.
             * @example 5fcec999-2bfb-4dd7-ba38-2d9e16c49149
             */
            sharing_id?: string;
            file: components["schemas"]["File"];
            format?: components["schemas"]["Format"];
            template?: components["schemas"]["Design"];
        };
        File: {
            /**
             * @description File type
             * @example jpeg
             * @enum {string}
             */
            type: "jpeg" | "png" | "pdf" | "gif" | "mp4" | "webm" | "zip";
            /**
             * @description URL of the banner (useful to download the image).
             * @example https://production-banners.s3.eu-west-1.amazonaws.com/demo/996739f4-b563-428a-a6e8-ec3cb8bd03d4.jpeg
             */
            url: string;
            /**
             * @description The CDN URL of the banner (useful to host the image; on a website for instance). (A bandwidth usage limit applies, related to your plan). (Not available for zip)
             * @example https://cdn.abyssale.com/demo/996739f4-b563-428a-a6e8-ec3cb8bd03d4.jpeg
             */
            cdn_url?: string;
            /**
             * @description Name of the file. If the related design contains a custom naming scheme, the custom name will be available from this property.
             * @example 996739f4-b563-428a-a6e8-ec3cb8bd03d4.jpeg
             */
            filename?: string;
        };
        Format: {
            /**
             * @description Identifier/name of the format.
             * @example facebook-post
             */
            id: string;
            /**
             * @description Width of the format.
             * @example 1200
             */
            width: number;
            /**
             * @description Height of the format.
             * @example 1200
             */
            height: number;
        };
        Design: {
            /**
             * Format: uuid
             * @description Unique identifier (UUID) of the design.
             * @example 64238d01-d402-474b-8c2d-fbc957e9d290
             */
            id: string;
            /**
             * @description Name of the design.
             * @example Ad campaign fall 2025
             */
            name: string;
            /**
             * @description Type of the design
             * @example static
             * @enum {string}
             */
            type: "static" | "animated" | "printer" | "printer_multipage";
            /**
             * @description Timestamp of when the design has been created.
             * @example 1649942114
             */
            created_at: number;
            /**
             * @description Timestamp of when the design has been updated for the last time.
             * @example 1649942114
             */
            updated_at: number;
            /**
             * @description Design Category
             * @example Fall campaigns
             */
            category_name?: string | null;
        };
        DesignFormat: {
            /**
             * @description Unique identifier (name) of the format.
             * @example facebook-post
             */
            id: string;
            /**
             * Format: uuid
             * @description Unique UUID of the format
             * @example 9b57d65e-eb2c-4a74-a51e-4482917c248a
             */
            uid: string;
            /**
             * @description Width of the format
             * @example 1200
             */
            width: number;
            /**
             * @description Height of the format
             * @example 1200
             */
            height: number;
            /**
             * @description Unit of measurement for dimensions
             * @example px
             */
            unit?: string;
            /**
             * Format: uri
             * @description Preview Image URL of the format
             * @example https://production-banners.s3-eu-west-1.amazonaws.com/templates/e0d292f2-ec21-11e9-a539-3c408bf94155/a9b3c668-7b84-4924-adf0-815dae727d32.png
             */
            preview_url?: string;
            /**
             * Format: uri
             * @description URL of the existing dynamic image for this format.
             * @example https://img.abyssale.com/ecf1fe8c-5392-48c2-b6d2-665183a18fe5/9b57d65e-eb2c-4a74-a51e-4482917c248a
             */
            dynamic_image_url?: string;
        };
        DesignElement: {
            /**
             * @description Layer name (`root` is a special element that allows to customize the image background color.)
             * @example element-name
             */
            name: string;
            /**
             * @description Layer type
             * @example text
             * @enum {string}
             */
            type: "container" | "text" | "button" | "image" | "logo" | "shape" | "illustration" | "rating" | "qrcode" | "chart" | "video" | "audio";
            /** @description List of all attributes */
            attributes: {
                /**
                 * @description The attribute name
                 * @example payload
                 */
                id: string;
                /**
                 * @description An helper to understand what is this attribute
                 * @example Text content (i.e. Lorem ipsum)
                 */
                help: string;
                /**
                 * @example {
                 *       "facebook-post": "My image title"
                 *     }
                 */
                values: {
                    [key: string]: string;
                };
            }[];
        };
        Font: {
            /**
             * Format: uuid
             * @description Font unique ID, this parameter can be used to force a specific font on a text or a button element.
             * @example 61568e7c-33c5-11ea-9877-92672c1b8195
             */
            id: string;
            /**
             * @description The font name
             * @example Ubuntu Mono
             */
            name: string;
            available_weights: ((100 | 200 | 300 | 400 | 500 | 600 | 700 | 800 | 900) | ("100-italic" | "200-italic" | "300-italic" | "400-italic" | "500-italic" | "600-italic" | "700-italic" | "800-italic" | "900-italic"))[];
            /**
             * @description Either `google` for the Google fonts or `custom` for your uploaded fonts.
             * @enum {string}
             */
            type: "google" | "custom";
        };
        RootElement: {
            background_color?: components["schemas"]["backgroundColor"];
        };
        Element: {
            /** @description `true`, `false`. If true it hides the current element */
            hidden?: boolean;
            /** @description 6-8 digits hexadecimal color */
            shadow_color?: string;
            /** @description Blur in pixels */
            shadow_blur?: number;
            /** @description Horizontal offset in pixels (can be negative) */
            shadow_offset_x?: number;
            /** @description Vertical offset in pixels (can be negative) */
            shadow_offset_y?: number;
        } & (components["schemas"]["TextElement"] | components["schemas"]["ImageElement"] | components["schemas"]["ButtonElement"] | components["schemas"]["LogoElement"] | components["schemas"]["ShapeElement"] | components["schemas"]["RatingElement"] | components["schemas"]["IllustrationElement"] | components["schemas"]["QRCodeElement"] | components["schemas"]["VideoElement"] | components["schemas"]["AudioElement"]);
        TextElement: {
            payload?: components["schemas"]["payload"];
            color?: components["schemas"]["color"];
            background_color?: components["schemas"]["backgroundColor"];
            background_padding?: components["schemas"]["backgroundPadding"];
            font_size?: components["schemas"]["fontSize"];
            font?: components["schemas"]["font"];
            font_weight?: components["schemas"]["fontWeight"];
            line_height?: components["schemas"]["lineHeight"];
            skew_y?: components["schemas"]["skewY"];
            alignment?: components["schemas"]["textAlignment"];
            stroke_width?: components["schemas"]["strokeWidth"];
            stroke_color?: components["schemas"]["strokeColor"];
            text_transform?: components["schemas"]["textTransform"];
            /** @description Automatically adjusts the text size to fit within its container. When true, `min_font_size` must also be defined. */
            auto_resize?: boolean;
            /** @description Minimum font size allowed when `auto_resize` is enabled. */
            min_font_size?: number;
            /** @description Maximum number of lines allowed. */
            max_lines?: number;
            /** @description Attempts to balance line lengths with a maximum variance of 20% between lines. Adjusts character spacing (±20), then reduces font size (up to -10px) if needed. */
            text_harmony?: boolean;
            /** @description If the text does not fit, it is truncated and an ellipsis (...) is appended. */
            text_truncation?: boolean;
            /**
             * @description Defines the side on which a border is rendered. Use `none` to disable an existing side border.
             * @enum {string}
             */
            side_border?: "left" | "right" | "top" | "bottom" | "none";
            /** @description Thickness of the side border in pixels. */
            side_border_thickness?: number;
            /** @description Color of the side border. 6-8 digits hexadecimal or cmyka (for print). */
            side_border_color?: string;
            /** @description Whether the border corners are rounded (true) or square (false). Default is false. */
            side_border_rounded?: boolean;
            /** @description Distance in pixels between the text content and the side border. Default is 0. */
            side_border_padding?: number;
            /** @description Moves the border along the perpendicular axis. Positive and negative values shift in opposite directions. Default is 0. */
            side_border_offset?: number;
            /** @description Extends the length of the border beyond the text bounding box by the specified number of pixels. Default is 0. */
            side_border_spread?: number;
            /**
             * @description Key-value pairs used to replace variables within the text payload.
             *     Variables are defined in the design as `{variableName}` placeholders.
             *     Pass the variable name (without braces) as the key and the replacement value as the value.
             * @example {
             *       "username": "Alice",
             *       "title": "Spring Sale"
             *     }
             */
            vars?: {
                [key: string]: string;
            };
        };
        ButtonElement: {
            payload?: components["schemas"]["payload"];
            color?: components["schemas"]["color"];
            background_color?: components["schemas"]["backgroundColor"];
            background_padding?: components["schemas"]["backgroundPadding"];
            font_size?: components["schemas"]["fontSize"];
            font?: components["schemas"]["font"];
            font_weight?: components["schemas"]["fontWeight"];
            line_height?: components["schemas"]["lineHeight"];
            text_transform?: components["schemas"]["textTransform"];
        };
        ImageElement: {
            image_url?: components["schemas"]["imageUrl"];
            image_encoded?: components["schemas"]["imageEncoded"];
            opacity?: components["schemas"]["opacity"];
            fitting_type?: components["schemas"]["fittingType"];
            alignment?: components["schemas"]["alignment"];
            mask_name?: components["schemas"]["maskName"];
            mask_properties?: components["schemas"]["maskProperties"];
            filter_name?: components["schemas"]["filterName"];
            filter_properties?: components["schemas"]["filterProperties"];
            overlay_direction?: components["schemas"]["overlayDirection"];
            overlay_color_1?: components["schemas"]["overlayColor1"];
            overlay_color_2?: components["schemas"]["overlayColor2"];
            /** @description Activates AI background removal when set to true. */
            remove_bg?: boolean;
            /** @description Additional settings for background removal. */
            remove_bg_properties?: {
                /** @description Trims the edges of the image after background removal. Default is false. */
                remove_bg_crop?: boolean;
            };
            /** @description Activates AI-powered auto-focus to detect and focus on specified objects or people within the image. */
            auto_focus?: boolean;
            /** @description Additional settings for auto-focus. */
            auto_focus_properties?: {
                /**
                 * @description Model used for focusing. `generic` for objects, `people` for human subjects, `face` for face detection. Default is `generic`.
                 * @enum {string}
                 */
                model?: "generic" | "people" | "face";
                /** @description List of object labels to focus on (generic model only). Uses Open Images Dataset labels. */
                focus_objects?: string[];
                /**
                 * @description Specific to `people` model. Defines which part of the subject to frame.
                 * @enum {string}
                 */
                focus_framing?: "face" | "head" | "shoulders" | "full_body";
                /**
                 * @description Specific to `people` model. Controls the zoom level applied. Default is `max`.
                 * @enum {string}
                 */
                focus_zoom?: "off" | "low" | "medium" | "max";
                /**
                 * @description Specific to `people` model. When multiple subjects are detected, defines which one to target. Default is `all`.
                 * @enum {string}
                 */
                focus_target?: "largest" | "left" | "middle" | "right" | "all";
            };
            /**
             * @description AI-generated image from a text prompt. Only available for asynchronous generation.
             *     If `image_url` (except default image) or `image_encoded` is provided, this property is ignored.
             * @example A sleek, modern glass villa situated in the middle of a minimalist lavender field.
             */
            text_to_image?: string;
        };
        LogoElement: {
            image_url?: components["schemas"]["imageUrl"];
            image_encoded?: components["schemas"]["imageEncoded"];
            alignment?: components["schemas"]["alignment"];
        };
        ShapeElement: {
            background_color?: components["schemas"]["backgroundColor"];
            pattern_name?: components["schemas"]["patternName"];
            pattern_color?: components["schemas"]["patternColor"];
            stroke_width?: components["schemas"]["strokeWidth"];
            stroke_color?: components["schemas"]["strokeColor"];
        };
        RatingElement: {
            rating_score?: components["schemas"]["ratingScore"];
            star_dimension?: components["schemas"]["starDimension"];
            star_margin?: components["schemas"]["starMargin"];
            star_color?: components["schemas"]["starColor"];
            background_color?: components["schemas"]["ratingBackgroundColor"];
        };
        IllustrationElement: {
            illustration_type?: components["schemas"]["illustrationType"];
            illustration_file?: components["schemas"]["illustrationFile"];
            illustration_properties?: components["schemas"]["illustrationProperties"];
            alignment?: components["schemas"]["alignment"];
            opacity?: components["schemas"]["opacity"];
        };
        QRCodeElement: {
            background_color?: components["schemas"]["qrcodeBackgroundColor"];
            foreground_color?: components["schemas"]["qrcodeForegroundColor"];
            payload?: components["schemas"]["qrcodePayload"];
            image_url?: components["schemas"]["qrcodeImageUrl"];
            hide_icon?: components["schemas"]["qrcodeHideIcon"];
        };
        /** @description This element is only available for animated design */
        VideoElement: {
            video_url?: components["schemas"]["videoUrl"];
        };
        /** @description Audio layer element. Only available for animated designs with MP4 output. */
        AudioElement: {
            /**
             * Format: uri
             * @description **HTTP(s) URL of the audio file.**
             *
             *     It must be a publicly accessible link with a filesize of 30 MB maximum.
             *
             *     Supported files: mp3, wav
             */
            audio_url?: string;
            /**
             * @description Volume level. 1 = default volume, 0.5 = half volume, 0 = silent. Default is 1.
             * @example 1
             */
            max_volume?: number;
            /**
             * @description Playback speed. 1 = 100%, 0.5 = 50%. Default is 1.
             * @example 1
             */
            speed?: number;
        };
        /** @description A `dictionary` containing all elements with properties you would like to override form the default design (keys correspond to layer names) */
        Elements: {
            [key: string]: components["schemas"]["RootElement"] | components["schemas"]["Element"] | components["schemas"]["VideoElement"] | components["schemas"]["AudioElement"];
        };
        /** @description A `dictionary` containing all pages with properties you would like to override form the default design (keys correspond to layer names) */
        Pages: {
            [key: string]: {
                root: components["schemas"]["RootElement"];
            };
        };
        DuplicationRequest: {
            /**
             * Format: uuid
             * @description Unique identifier for tracking the duplication process
             * @example 40c32a4e-4869-11f0-96f2-0a00d9eb8f78
             */
            duplication_request_id: string;
        };
        DuplicationRequestStatus: {
            /**
             * Format: uuid
             * @description Unique identifier of the duplication request
             * @example 40c32a4e-4869-11f0-96f2-0a00d9eb8f78
             */
            request_id: string;
            /**
             * @description Current status of the duplication request
             * @example COMPLETED
             * @enum {string}
             */
            status: "INIT" | "IN_PROGRESS" | "ERROR" | "COMPLETED";
            /**
             * @description Unix timestamp when the duplication request was created
             * @example 1749827734
             */
            created_at_ts: number;
            /**
             * @description Unix timestamp when the duplication was completed (null if not completed)
             * @example 1749827736
             */
            completed_at_ts?: number | null;
            /**
             * @description Unix timestamp when the duplication failed (null if not failed)
             * @example null
             */
            errored_at_ts?: number | null;
            target_project: components["schemas"]["ProjectSummary"];
            /** @description List of duplicated designs (empty if not completed) */
            designs: components["schemas"]["DuplicatedDesign"][];
        };
        ProjectSummary: {
            /**
             * Format: uuid
             * @description Unique identifier of the project
             * @example d59adee9-4867-11f0-96f2-0a00d9eb8f78
             */
            id: string;
            /**
             * @description Name of the project
             * @example HTML5 Tests
             */
            name: string;
            /**
             * @description Unix timestamp when the project was created
             * @example 1749827125
             */
            created_at_ts: number;
        };
        DuplicatedDesign: {
            /**
             * Format: uuid
             * @description ID of the original workspace template
             * @example 0c967bd0-4137-4690-ad70-249aa021c68b
             */
            original_design_id: string;
            /**
             * Format: uuid
             * @description ID of the newly created template in your project
             * @example afb1a61a-6c50-4bc3-a49b-3381822d4e81
             */
            target_design_id: string;
            /**
             * @description Name of the duplicated template
             * @example Design Name
             */
            target_design_name: string;
        };
        GenerationRequestStatus: {
            /**
             * Format: uuid
             * @description Unique identifier of the generation request
             */
            id: string;
            /** @description Whether the generation is complete. `false` when the request returns 202, `true` when it returns 200. */
            is_finalized: boolean;
            /** @description List of generated files (populated once finalized) */
            banners: components["schemas"]["Banner"][];
            /** @description Per-format errors, if any occurred during generation */
            errors?: {
                /** @description The format name that failed to generate */
                template_format_name?: string;
                /** @description The error reason */
                reason?: string;
            }[];
        };
        /**
         * @example {
         *       "id": "a12b3c4d-5e6f-7890-abcd-ef1234567890",
         *       "design_id": "b2c3d4e5-f6a7-8901-bcde-f12345678901",
         *       "formats": [
         *         {
         *           "id": "one-format",
         *           "uid": "11111111-2222-3333-4444-555555555555",
         *           "width": 3333,
         *           "unit": "px",
         *           "height": 666,
         *           "dynamic_image_url": "https://img.abyssale.com/a12b3c4d-5e6f-7890-abcd-ef1234567890/one-format"
         *         },
         *         {
         *           "id": "another-format",
         *           "uid": "66666666-7777-8888-9999-000000000000",
         *           "width": 1920,
         *           "unit": "px",
         *           "height": 1080,
         *           "dynamic_image_url": "https://img.abyssale.com/a12b3c4d-5e6f-7890-abcd-ef1234567890/another-format"
         *         }
         *       ]
         *     }
         */
        DynamicImageResponse: {
            /**
             * Format: uuid
             * @description Unique ID of the dynamic image
             */
            id: string;
            /**
             * Format: uuid
             * @description Design ID associated with this dynamic image
             */
            design_id: string;
            /** @description List of formats available for this dynamic image */
            formats: {
                /** @description Format name */
                id: string;
                /** @description Format unique identifier (UUID) */
                uid: string;
                /** @description Width of the format in pixels */
                width: number;
                /** @description Unit of measurement for dimensions, e.g. px */
                unit: string;
                /** @description Height of the format in pixels */
                height: number;
                /**
                 * Format: uri
                 * @description URL to the dynamically generated image for this format
                 */
                dynamic_image_url: string;
            }[];
        };
        /**
         * @description **The background color displayed behind the element.**
         *
         *     3 filling modes are available:
         *     - `Monochrome`: 6 or 8 hexadecimal colors starting with a **#**. _i.e. #EAEAEA or #FF00FF55_
         *     - `Linear Gradient`: `linear-gradient(x1% y1% x2% y2%,offset1% #color1 opacity1,offset2% #color2 opacity2)` _i.e. linear-gradient(0% 0% 100% 0%,0% #1a47ff 1,100% #b65151 1)_
         *     - `Cmyka` (print only): `cmyka(c,m,y,k)` or `cmyka(c,m,y,k,alpha)` where each value is 0–100. _i.e. cmyka(0,100,100,0,100)_
         * @example #FF0000
         */
        backgroundColor: string;
        /**
         * @description **The text content**. *Example: Lorem Ipsum*
         *
         *     - [How can I force specific line breaks?](https://developers.abyssale.com/image-generation-properties.html#color)
         *     - [How can I add decorations to specific parts of a text?](https://developers.abyssale.com/image-generation-properties.html#color)
         */
        payload: string;
        /**
         * @description **The text color.**
         *
         *     3 filling modes are available:
         *     - `Monochrome`: 6 or 8 hexadecimal colors starting with a **#**. _i.e. #EAEAEA or #FF00FF55_
         *     - `Linear Gradient`: `linear-gradient(x1% y1% x2% y2%,offset1% #color1 opacity1,offset2% #color2 opacity2)`
         *     - `Cmyka` (print only): `cmyka(c,m,y,k)` or `cmyka(c,m,y,k,alpha)` where each value is 0–100.
         */
        color: string;
        /**
         * @description **The padding of the background color around the text.** *Example: 10*
         *
         *     _This parameter will only be used if a background color is defined._
         *
         *     - String: Two numbers separated by a space: First number represents the vertical padding in pixels & the second the vertical padding. For instance: 0 10 : 0 as vertical padding & 10 as horizontal
         *     - Number: Paddings (Horizontal & vertical) in pixels. _i.e. 10_
         */
        backgroundPadding: string;
        /** @description **Font size in pixels** *Example: 20* */
        fontSize: number;
        /**
         * Format: uuid
         * @description **Force a specific font by ID**. *Example: 6156907e-33c5-11ea-9877-92672c1b8195*
         *
         *     The fonts list is available by calling the [GET /fonts](#tag/Fonts) API route.
         */
        font: string;
        /**
         * @description **Force a font weight**. *Example: 500*
         *
         *     | Value | Corresponding name |
         *     |-----|-----|
         *     | 100   | Thin   |
         *     | 200   | Extra Light   |
         *     | 300   | Light   |
         *     | 400   | Regular   |
         *     | 500   | Medium   |
         *     | 600   | Semi Bold   |
         *     | 700   | Bold   |
         *     | 800   | Extra Bold   |
         *     | 900   | Black   |
         *
         *     _If the font does not contain the given font weight, the nearest weight will be used._
         * @enum {number}
         */
        fontWeight: 100 | 200 | 300 | 400 | 500 | 600 | 700 | 800 | 900;
        /**
         * @description **Force line height in percentage** *Example: 130*
         *
         *     __This parameter is only applied when the text is a multiline one.__
         */
        lineHeight: number;
        /** @description **Slant text on the y axis** *Example: 20* */
        skewY: number;
        /**
         * @description **The text alignment.** *Example: left*
         *
         *     __If given, the text position will be computed from the text bounding box defined within the design.__
         * @enum {string}
         */
        textAlignment: "top" | "middle" | "bottom" | "left" | "center" | "right" | "top left" | "top center" | "top right" | "middle left" | "middle center" | "middle right" | "bottom left" | "bottom right" | "bottom center";
        /**
         * @description **Text transformation style.** Force the text to be transformed to one of the following options: - `uppercase`: All letters become uppercase (e.g., `EXAMPLE`) - `lowercase`: All letters become lowercase (e.g., `example`) - `titlecase`: The first letter of each word is capitalized (e.g., `Example Text`) - `capitalize`: Only the first letter of the entire text is capitalized (e.g., `Example text`)
         * @enum {string}
         */
        textTransform: "uppercase" | "lowercase" | "titlecase" | "capitalize";
        /** @description **Width of the stroke** *Example: 10* */
        strokeWidth: number;
        /**
         * @description **Stroke Color. 6-8 digits Hexa color.**. *Example: #FF0000*
         *
         *     __If your design does not contain any stroke, this color won't be visible__
         */
        strokeColor: string;
        /**
         * Format: uri
         * @description **HTTP(s) URL of the image** *Example: https://www.abyssale.com/imge/abyssale_logo.png*
         *
         *     __It must be a public accessible link and have a filesize of 10 mo maximum.__
         *
         *     Supported files: jpeg, png, webp, svg, gif
         */
        imageUrl: string;
        /**
         * @description **Base64 encoded image as value.** *Example: /9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAIBAQE...*
         *
         *     __If the image_url is given, this parameter will not be used.__
         */
        imageEncoded: string;
        /** @description **Opacity of the image** *Example: 60* */
        opacity: number;
        /**
         * @description **Defines the way the image will be inserted in the bounding box**
         *
         *     Two properties are supported:
         *
         *     - `cover`: It will force the image to fill entirely the area without changing the aspect ratio (hence the image will be cropped if its ratio is not the same as the container)
         *     - `fill`: The image will be displayed entirely within the box.
         * @enum {string}
         */
        fittingType: "cover" | "fill";
        /**
         * @description **The image alignment.** *Example: left*
         * @enum {string}
         */
        alignment: "top" | "middle" | "bottom" | "left" | "center" | "right" | "top left" | "top center" | "top right" | "middle left" | "middle center" | "middle right" | "bottom left" | "bottom right" | "bottom center";
        /**
         * @description **A mask can be added to the image**.
         *
         *     5 masks are available:
         *     - `circle`: The image will be rendered as a circle. No additional property is available.
         *     - `rounded_corners`: Corners of the image will be rounded. It requires another property: `mask_properties`.
         *     - `blob`: The image will be rendered as a blob. No additional property is available.
         *     - `squircle`: The image will be rendered as a squircle. No additional property is available.
         *     - `pentagon`: The image will be rendered as a pentagon. No additional property is available.
         *     - `hexagon`: The image will be rendered as a hexagon. No additional property is available.
         *     - `parallelogram`: The image will be rendered as a parallelogram. No additional property is available.
         * @enum {string}
         */
        maskName: "circle" | "rounded_corners" | "blob" | "squircle" | "pentagon" | "hexagon" | "parallelogram";
        /**
         * @description **When the rounded_corners mask is applied, this parameter allows to define the radius**.
         *
         *     Two types of radius is supported:
         *     - A number, that allows to define all corners' radius at once. *Example: {"radius": 20}*
         *     - An object, that allows to customize each corner's radius individually.
         *       4 properties are available: (`tl` = top left, `tr` = top right, `br` = bottom right, `bl` = bottom left)
         *
         *     *Example: {"radius": {
         *       "tl": 0,
         *       "tr": 56,
         *       "br": 56,
         *       "bl": 20
         *     }}*
         */
        maskProperties: {
            radius?: number | Record<string, never>;
        };
        /**
         * @description **A filter can be added to the image.** *Example: grayscale*
         *
         *     2 filters are available:
         *     - `grayscale`: It converts the input image to grayscale. No additional property is available.
         *     - `duotone`: Apply a duotone filter to the image. It requires another property: `filter_properties`
         * @enum {string}
         */
        filterName: "grayscale" | "duotone";
        /**
         * @description **When the duotone mask is applied, this parameter allows to define the duotone filter to apply**.
         *     *Example: { "name": "blue_orange" }*
         */
        filterProperties: {
            /** @enum {string} */
            name?: "blue_orange" | "deep_green_light_green" | "BrightRed_light_yellow" | "brown_pale_green" | "brown_beige" | "deep_blue_green" | "deep_blue_red" | "deep_purple_orange" | "deep_purple_beige" | "deep_purple_pale_green" | "deep_blue_pale_green";
        };
        /**
         * @description **A pattern can be added to the shape**.
         *
         *     (List of patterns)[]
         * @enum {string}
         */
        patternName: "bubbles" | "cage" | "cross" | "doubleCircle" | "drops" | "parkay" | "pills" | "plus" | "star" | "ticTac" | "ticTacFilled" | "triangle" | "wiggle";
        /**
         * @description **A 6 or 8 hexadecimal shape color starting with a `#`.** *Example: #EAEAEA or #FF00FF55*
         *
         *     _If no pattern is applied to the shape, this property will not change anything._
         * @example #EAEAEA
         */
        patternColor: string;
        /**
         * @description Direction of the overlay.
         * @enum {string}
         */
        overlayDirection: "horizontal" | "vertical" | "diagonal";
        /** @description First color of the overlay. 6-8 Digits Hexa color. */
        overlayColor1: string;
        /** @description Second color of the overlay. 6-8 Digits Hexa color. */
        overlayColor2: string;
        /**
         * @description **Score of the rating on a scale of 100.** *Example: 50*
         *
         *     _For instance, as rating is displayed as five-stars, 50 will give a 2.5/5 score._
         */
        ratingScore: number;
        /**
         * @description **The background color displayed behind all the stars.**
         *
         *     6 or 8 hexadecimal colors starting with a **#**. _i.e. #EAEAEA or #FF00FF55_
         */
        ratingBackgroundColor: string;
        /**
         * @description **The color of the filled stars.**
         *
         *     6 or 8 hexadecimal colors starting with a **#**. _i.e. #EAEAEA or #FF00FF55_
         */
        starColor: string;
        /** @description **Margins in pixels between stars.** *Example: 60* */
        starMargin: number;
        /** @description **Size in pixels of one star.** *Example: 100* */
        starDimension: number;
        /** @description **The illustration library used to retrieved the illustration name. Can be: undraw, feather, twemoji or material_icons.**. */
        illustrationType: string;
        /** @description **The illustration name.**. */
        illustrationFile: string;
        /** @description **Only `Undraw`, `feather` and `material icons` support `illustration_properties`.** */
        illustrationProperties: {
            /**
             * @description **Color of the illustration**
             *
             *     *A 6 or 8 hexadecimal shape color starting with a **#**.** *Example: #EAEAEA or #FF00FF55_*
             */
            primary_color?: string;
        };
        /**
         * @description **The background color displayed behind the qrcode.**
         *
         *     6 or 8 hexadecimal colors starting with a **#**. _i.e. #EAEAEA or #FF00FF55_
         */
        qrcodeBackgroundColor: string;
        /**
         * @description **The color of the qrcode (of all squares).**
         *
         *     6 or 8 hexadecimal colors starting with a **#**. _i.e. #EAEAEA or #FF00FF55_
         */
        qrcodeForegroundColor: string;
        /**
         * @description **The content of the qrcode. i.e. Lorem Ipsum**
         *
         *     This content will be displayed once the QR Code is scanned.
         */
        qrcodePayload: string;
        /**
         * @description **HTTP(s) URL of the icon displayed in the middle of the QR Code** *Example: https://www.abyssale.com/imge/abyssale_logo.png*
         *
         *     __It must be a public accessible link and have a filesize of 10 mo maximum.__
         *
         *     Supported files: jpeg, png, webp
         */
        qrcodeImageUrl: string;
        /** @description `true`, `false`. If true it hides the icon in the middle of the QRCode. */
        qrcodeHideIcon: boolean;
        /**
         * Format: uri
         * @description **HTTP(s) URL of the video** *Example: https://www.abyssale.com/imge/this_an_example.mp4*
         *
         *     __It must be a public accessible link and have a filesize of 100 mo maximum.__
         *
         *     Supported files: mp4
         */
        videoUrl: string;
    };
    responses: {
        /** @description Bad Request — the request body or parameters are invalid. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Unauthorized — missing or invalid API key. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Not Found — the requested resource does not exist. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Too Many Requests — request rate limit exceeded (10 req/s). */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "message": "429 Too Many Requests",
                 *       "id": "rate_limit_exceeded"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /**
         * @description Plan or credit restriction — the account does not have sufficient credits or the
         *     requested output format is not included in the current plan.
         *
         *     > **Note:** The API returns these errors as HTTP `429` rather than `402`. Distinguish
         *     > them from rate-limit errors by inspecting the `message` field.
         */
        PaymentRequired: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Internal Server Error — an unexpected error occurred on our side. */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "message": "Internal server error",
                 *       "id": "internal_server_error"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listDesigns: {
        parameters: {
            query?: {
                /** @description Unique identifier (UUID) of a project. Filter designs by project. */
                project_id?: string;
                /** @description Filter designs by one of these types static, animated, printer, printer_multipage */
                type?: "static" | "animated" | "printer" | "printer_multipage";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": (components["schemas"]["Design"] & {
                        /**
                         * Format: uri
                         * @description Preview Image URL of the first design format
                         * @example https://production-banners.s3-eu-west-1.amazonaws.com/templates/e0d292f2-ec21-11e9-a539-3c408bf94155/a9b3c668-7b84-4924-adf0-815dae727d32.png
                         */
                        preview_url?: string;
                    })[];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getDesign: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier (UUID) of the design */
                designId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Design"] & {
                        /**
                         * @description The list of formats available in the design.
                         *
                         *     The id property can be used to specify the format you would like to generate in the generation API call.
                         */
                        formats?: components["schemas"]["DesignFormat"][];
                        /**
                         * @description The list of all elements (& customizable properties) contained in the design.
                         *
                         *     `name` is the layer name (root is a special element that allows to customize the image background color.)
                         *
                         *     `attributes` contains the list of all customizable properties:
                         *     - `id`: The attribute ID
                         *     - `values`: the related value for this attribute in each format (if defined)
                         */
                        elements?: components["schemas"]["DesignElement"][];
                        /**
                         * @description Variables used within the text layers of the design.
                         *     Keys represent variable names (without braces), and values
                         *     represent the placeholder format in the design (e.g. "{name}").
                         * @example {
                         *       "name": "{name}",
                         *       "title": "{title}"
                         *     }
                         */
                        variables?: {
                            [key: string]: string;
                        };
                    };
                };
            };
            /** @description Design Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getDesignFormat: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the design */
                designId: string;
                /** @description Format name or UID */
                formatSpecifier: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Format details retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Format identifier
                         * @example new-format
                         */
                        id?: string;
                        /**
                         * Format: uuid
                         * @description Unique ID for the format instance
                         * @example 6248b96f-581a-43f0-9863-85e1b7d0ec05
                         */
                        uid?: string;
                        /**
                         * @description Width of the format in specified units
                         * @example 3333
                         */
                        width?: number;
                        /**
                         * @description Height of the format in specified units
                         * @example 666
                         */
                        height?: number;
                        /**
                         * @description Unit of measurement for dimensions
                         * @example px
                         */
                        unit?: string;
                        /**
                         * Format: uri
                         * @description URL to preview image of this format
                         * @example https://production-banners.s3-eu-west-1.amazonaws.com/templates/e0d292f2-ec21-11e9-a539-3c408bf94152/21aff1a9-bcde-4294-8320-be6cae651381.png
                         */
                        preview_url?: string;
                        /**
                         * Format: uri
                         * @description URL to the dynamically generated image
                         * @example https://img.abyssale.com/673f0cb6-f1f6-4f7d-8ea2-4a0ed317efbe/6248b96f-581a-43f0-9863-85e1b7d0ec0a
                         */
                        dynamic_image_url?: string;
                        design?: components["schemas"]["Design"];
                        /** @description List of all elements (& customizable properties) contained in the design format */
                        elements?: {
                            /**
                             * @description Element name
                             * @example root
                             */
                            name?: string;
                            /**
                             * @description Element type
                             * @example container
                             */
                            type?: string;
                            settings?: {
                                /**
                                 * @description Whether the element is mandatory
                                 * @example false
                                 */
                                is_mandatory?: boolean;
                            };
                            attributes?: {
                                /**
                                 * @description Attribute identifier
                                 * @example background_color
                                 */
                                id?: string;
                                /**
                                 * @description Help text for the attribute
                                 * @example 6 or 8 digits hexadecimal background color (i.e. #F3F3F3) of the banner
                                 */
                                help?: string;
                                /**
                                 * @description Value of the attribute for this format
                                 * @example #FFFFFF
                                 */
                                value?: string;
                            }[];
                            layout?: {
                                /** @example 0 */
                                x?: number;
                                /** @example 0 */
                                y?: number;
                                /** @example 3333 */
                                width?: number;
                                /** @example 666 */
                                height?: number;
                            };
                        }[];
                        /**
                         * @description Variables used within the text layers of the design format (if any).
                         *     Keys represent variable names (without braces), and values
                         *     represent the placeholder format in the design (e.g. "{name}").
                         * @example {
                         *       "name": "{name}",
                         *       "title": "{title}"
                         *     }
                         */
                        variables?: {
                            [key: string]: string;
                        };
                    };
                };
            };
            /** @description Format Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createDynamicImageUrl: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the design */
                designId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "enable_rate_limit": true,
                 *       "enable_production_mode": true
                 *     }
                 */
                "application/json": {
                    /**
                     * @description Enable API rate limiting for this dynamic image
                     * @default false
                     */
                    enable_rate_limit?: boolean;
                    /**
                     * @description Enable Production mode for this dynamic image
                     * @default false
                     */
                    enable_production_mode?: boolean;
                };
            };
        };
        responses: {
            /** @description Existing dynamic image retrieved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DynamicImageResponse"];
                };
            };
            /** @description Dynamic image successfully created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DynamicImageResponse"];
                };
            };
            /** @description Design Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier (UUID) of the file */
                bannerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Banner"];
                };
            };
            /** @description A banner with the specified ID was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    generateImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier (UUID) of the design */
                designId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    elements: components["schemas"]["Elements"];
                    /**
                     * @description Corresponds to the format ID you would like to generate (only mandatory when your design contains several formats).
                     * @example facebook-post
                     */
                    template_format_name?: string;
                    /**
                     * @description Output file type. Defaults to the design's configured type when omitted.
                     * @enum {string}
                     */
                    image_file_type?: "png" | "jpeg" | "webp" | "avif" | "pdf" | "auto";
                    /**
                     * @description Percentage of compression applied.
                     * @example 80
                     */
                    file_compression_level?: number;
                };
            };
        };
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Banner"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            /**
             * @description Rate limit exceeded (10 req/s) **or** plan/credit restriction.
             *     Inspect the `message` field to distinguish the two causes — see the
             *     [`TooManyRequests`](#/components/responses/TooManyRequests) and
             *     [`PaymentRequired`](#/components/responses/PaymentRequired) components
             *     for the full list of possible messages.
             */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    generateMultiFormatMedia: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier (UUID) of the design */
                designId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    elements: components["schemas"]["Elements"];
                    /**
                     * @description **Format IDs you would like to generate**.
                     *
                     *     _The array can be empty or not provided if you want to generate all formats of this design._
                     * @example [
                     *       "facebook-feed",
                     *       "instagram-post",
                     *       "iab-medium"
                     *     ]
                     */
                    template_format_names?: string[];
                    /**
                     * Format: uri
                     * @description **The url that will be called once generation of your images is done.**
                     *
                     *     We will do a `POST` request of the [NewBannerBatch](#operation/newBannerBatch) event on this URL with a JSON payload.
                     */
                    callback_url?: string;
                    /**
                     * @description Output file type. Depends on the design type (static/animated/printer). Defaults to the design's configured type when omitted.
                     * @enum {string}
                     */
                    image_file_type?: "png" | "jpeg" | "webp" | "avif" | "gif" | "pdf" | "html5" | "mp4" | "webm" | "auto";
                    /** @description Percentage of compression applied. */
                    file_compression_level?: number;
                    /** @description HTML5 output options (animated designs only) */
                    html5?: {
                        /** @default Abyssale page title example */
                        page_title?: string;
                        /** @default https://www.abyssale.com */
                        click_tag?: string;
                        /**
                         * @description Ad network identifier (e.g. "default", "doubleclick", "sizmek")
                         * @default default
                         */
                        ad_network?: string;
                        include_backup_image?: boolean | null;
                        /** @description Number of loop repetitions. -1 = infinite. */
                        repeat?: number | null;
                    };
                    /** @description GIF output options (animated designs only) */
                    gif?: {
                        max_fps?: number;
                        /** @description Number of loop repetitions. -1 = infinite. */
                        repeat?: number;
                    };
                    /** @description Video output options (animated designs only) */
                    video?: {
                        fps?: number;
                    };
                    /** @description Print output options (printer/printer_multipage designs only) */
                    print?: {
                        /**
                         * Format: uuid
                         * @description UUID of the color profile to apply
                         */
                        color_profile?: string;
                        display_crop_marks?: boolean;
                    };
                    /**
                     * Format: uuid
                     * @description UUID of the original visual this generation is based on.
                     */
                    original_visual_id?: string;
                };
            };
        };
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * Format: uuid
                         * @description Unique identifier (UUID) of the batch generation
                         */
                        generation_request_id?: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            /**
             * @description Rate limit exceeded (10 req/s) **or** plan/credit restriction.
             *     Inspect the `message` field to distinguish the two causes — see the
             *     [`TooManyRequests`](#/components/responses/TooManyRequests) and
             *     [`PaymentRequired`](#/components/responses/PaymentRequired) components
             *     for the full list of possible messages.
             */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    listFonts: {
        parameters: {
            query?: {
                /** @description Filter fonts by type. Omit to return both Google and custom fonts. */
                type?: "google" | "custom";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Font"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    exportBanners: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description An array of string that corresponds to the banners IDs you would like to export. */
                    ids: string[];
                    /**
                     * Format: uri
                     * @description The url that will be called once the generation of your export is done.
                     * @example https://your-webhook.com/export-abyssale
                     */
                    callback_url?: string;
                };
            };
        };
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Unique identifier (UUID) of the asynchronous export. Keep it to be able to identify the asynchronous response.
                         * @example 64238d01-d402-474b-8c2d-fbc957e9d290
                         */
                        export_id: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    generateMultiPagePdf: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier (UUID) of the design */
                designId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    pages: components["schemas"]["Pages"];
                    /**
                     * Format: uri
                     * @description **The url that will be called once generation of your PDF is done.**
                     *
                     *     We will do a `POST` request of the [NewBannerBatch](#operation/newBannerBatch) event on this URL with a JSON payload.
                     */
                    callback_url?: string;
                    /** @description Print output options */
                    print?: {
                        /**
                         * Format: uuid
                         * @description UUID of the color profile to apply
                         */
                        color_profile?: string;
                        display_crop_marks?: boolean;
                    };
                    /**
                     * Format: uuid
                     * @description UUID of the original visual this generation is based on.
                     */
                    original_visual_id?: string;
                };
            };
        };
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * Format: uuid
                         * @description Unique identifier (UUID) of the batch generation
                         */
                        generation_request_id?: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            /**
             * @description Rate limit exceeded (10 req/s) **or** plan/credit restriction.
             *     Inspect the `message` field to distinguish the two causes — see the
             *     [`TooManyRequests`](#/components/responses/TooManyRequests) and
             *     [`PaymentRequired`](#/components/responses/PaymentRequired) components
             *     for the full list of possible messages.
             */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    getGenerationRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier (UUID) of the generation request */
                generationRequestId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationRequestStatus"];
                };
            };
            /** @description Generation still in progress */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationRequestStatus"];
                };
            };
            /** @description Generation request not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listProjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSummary"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description Name of the project
                     * @example Summer Campaign 2024
                     */
                    name: string;
                };
            };
        };
        responses: {
            /** @description Project created successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSummary"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    duplicateWorkspaceTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Unique identifier (UUID) of the workspace template to duplicate
                 * @example 0c967bd0-4137-4690-ad70-249aa021c68b
                 */
                companyTemplateId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: uuid
                     * @description Target project ID where the template will be duplicated
                     * @example d59adee9-4867-11f0-96f2-0a00d9eb8f78
                     */
                    project_id: string;
                    /**
                     * @description Optional custom name for the duplicated template
                     * @example My Custom Template
                     */
                    name?: string;
                };
            };
        };
        responses: {
            /** @description Duplication request accepted and processing */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DuplicationRequest"];
                };
            };
            /** @description Workspace template Or Project not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getDuplicationRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Unique identifier (UUID) of the duplication request
                 * @example 40c32a4e-4869-11f0-96f2-0a00d9eb8f78
                 */
                duplicateRequestId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Duplication request status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DuplicationRequestStatus"];
                };
            };
            /** @description Duplication request not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
